#!/bin/bash
#######################
# ~/bin/dwm-statusbar #
#    Aram1d Config    #
#######################

# Status bar for dwm. Expanded from:
# https://bitbucket.org/jasonwryan/eeepc/src/73dadb289dead8ef17ef29a9315ba8f1706927cb/Scripts/dwm-status

# Colour codes from dwm/config.h (statuscolor patched).
cr_nrm="\x01"
cr_grn="\x04"
cr_mag="\x05"
cr_cya="\x06"
cr_blu="\x07"
cr_yel="\x08"
cr_org="\x09"


# Icon glyphs from font siji.pcf
glyph_msc="\uE205" #
glyph_cpu="\uE026" #
glyph_mem="\uE020" #
glyph_dl="\uE011"
glyph_ul="\uE012"
glyph_pac="\uE00F" #
glyph_com="\uE013"
glyph_eml="\uE014"
glyph_vol="\uE152" #
glyph_dat="\uE225" #
glyph_tim="\uE128" #
glyph_tor="\uE074" #
glyph_ety="\uE013" 

#All information given by statusbar are obtained via functions.

print_mem_used() {
  mem_used="$(free -m | awk 'NR==2 {print $3}')"
  echo -ne "${cr_blu}${glyph_mem} ${mem_used}M"
}

print_volume() {
  volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
  echo -ne "${cr_nrm}${glyph_vol}${volume}%"
}

print_sys_entropy() {
    sys_entropy=$(bc -l <<< "scale=1; $(cat /proc/sys/kernel/random/entropy_avail)/1000")
    [ $(echo "$sys_entropy > 2" | bc -l) ] && sys_entropy_cr=$cr_blu || sys_entropy_cr=$cr_mag
    echo -ne "${sys_entropy_cr}${glyph_ety}${sys_entropy} kb"

    }
 
print_sys_upd() {
    sys_upd_count=$(pacman -Qu | wc -l)

     [ $sys_upd_count -eq 0 ] && sys_upd_cr=$cr_blu
     [[ ($sys_upd_count -gt 1) && ($sys_upd_count -le 20) ]] && sys_upd_cr=$cr_org
     [ $sys_upd_count -gt 20 ] && sys_upd_cr=$cr_mag

    echo -ne "${sys_upd_cr}\uE00F:${sys_upd_count}"
    }

print_datetime() {
  datetime="$(date "+${glyph_dat}%a %d.%m ${glyph_tim}%H:%M")"
  echo -ne "${cr_grn}${datetime}"
}

# Pipe to status bar, not indented due to printing extra spaces/tabs
  xsetroot -name "$(print_sys_entropy)$(print_mem_used)$(print_volume)$(print_sys_upd)$(print_datetime)"
